require 'xcjobs'

xcode_version = `xcodebuild -version`.split("\n").first.scan(/\d+/).join('.')

if xcode_version.start_with?('8.0')
  def destinations(platform: 'iphonesimulator')
    if platform == 'iphonesimulator'
      [ 'name=iPhone 5,OS=10.0',
        'name=iPhone 5s,OS=10.0',
        'name=iPhone 6,OS=10.0',
        'name=iPhone 6s Plus,OS=10.0',
        'name=iPhone SE,OS=10.0',
        'name=iPad Air 2,OS=10.0',
        'name=iPad Pro (9.7 inch),OS=10.0',
        'name=iPad Pro (12.9 inch),OS=10.0'
      ]
    elsif platform == 'watchsimulator'
      [ 'name=Apple Watch - 38mm,OS=3.0',
        'name=Apple Watch - 42mm,OS=3.0'
      ]
    elsif platform == 'appletvsimulator'
      [ 'name=Apple TV 1080p,OS=10.0'
      ]
    else
      []
    end
  end
elsif xcode_version.start_with?('7.3') || xcode_version.start_with?('7.2')
  def destinations(platform: 'iphonesimulator')
    if platform == 'iphonesimulator'
      [ 'name=iPad 2,OS=8.1',
        'name=iPad Air,OS=8.1',
        'name=iPhone 4s,OS=8.1',
        'name=iPhone 4s,OS=8.3',
        'name=iPhone 4s,OS=8.4',
        'name=iPhone 4s,OS=9.0',
        'name=iPhone 4s,OS=9.2',
        'name=iPhone 5,OS=8.1',
        'name=iPhone 5s,OS=8.1',
        'name=iPhone 6,OS=8.1',
        'name=iPhone 6,OS=8.2',
        'name=iPhone 6,OS=8.3',
        'name=iPhone 6,OS=8.4',
        'name=iPhone 6,OS=9.0',
        'name=iPhone 6,OS=9.2',
        'name=iPhone 6 Plus,OS=8.1',
        'name=iPhone 6 Plus,OS=8.2',
        'name=iPhone 6 Plus,OS=8.3',
        'name=iPhone 6 Plus,OS=8.4',
        'name=iPhone 6 Plus,OS=9.0',
        'name=iPhone 6 Plus,OS=9.2'
      ]
    elsif platform == 'watchsimulator'
      [ 'name=Apple Watch - 38mm,OS=2.0',
        'name=Apple Watch - 42mm,OS=2.0',
        'name=Apple Watch - 38mm,OS=2.1',
        'name=Apple Watch - 42mm,OS=2.1',
      ]
    elsif platform == 'appletvsimulator'
      [ 'name=Apple TV 1080p,OS=9.0',
        'name=Apple TV 1080p,OS=9.1',
      ]
    else
      []
    end
  end
elsif xcode_version.start_with?('7.1')
  def destinations(platform: 'iphonesimulator')
    if platform == 'iphonesimulator'
      [ 'name=iPad 2,OS=8.1',
        'name=iPad Air,OS=8.1',
        'name=iPhone 4s,OS=8.1',
        'name=iPhone 4s,OS=8.3',
        'name=iPhone 4s,OS=8.4',
        'name=iPhone 4s,OS=9.0',
        'name=iPhone 4s,OS=9.1',
        'name=iPhone 5,OS=8.1',
        'name=iPhone 5s,OS=8.1',
        'name=iPhone 6,OS=8.1',
        'name=iPhone 6,OS=8.2',
        'name=iPhone 6,OS=8.3',
        'name=iPhone 6,OS=8.4',
        'name=iPhone 6,OS=9.0',
        'name=iPhone 6,OS=9.1',
        'name=iPhone 6 Plus,OS=8.1',
        'name=iPhone 6 Plus,OS=8.2',
        'name=iPhone 6 Plus,OS=8.3',
        'name=iPhone 6 Plus,OS=8.4',
        'name=iPhone 6 Plus,OS=9.0',
        'name=iPhone 6 Plus,OS=9.1'
      ]
    elsif platform == 'watchsimulator'
      [ 'name=Apple Watch - 38mm,OS=2.0',
        'name=Apple Watch - 42mm,OS=2.0',
      ]
    elsif platform == 'appletvsimulator'
      [ 'name=Apple TV 1080p,OS=9.0',
      ]
    else
      []
    end
  end
elsif xcode_version.start_with?('7.0')
  def destinations(platform: 'iphonesimulator')
    if platform == 'iphonesimulator'
      [ 'name=iPad 2,OS=8.1',
        'name=iPad Air,OS=8.1',
        'name=iPhone 4s,OS=8.1',
        'name=iPhone 4s,OS=8.3',
        'name=iPhone 4s,OS=8.4',
        'name=iPhone 4s,OS=9.0',
        'name=iPhone 5,OS=8.1',
        'name=iPhone 5s,OS=8.1',
        'name=iPhone 6,OS=8.1',
        'name=iPhone 6,OS=8.2',
        'name=iPhone 6,OS=8.3',
        'name=iPhone 6,OS=8.4',
        'name=iPhone 6,OS=9.0',
        'name=iPhone 6 Plus,OS=8.1',
        'name=iPhone 6 Plus,OS=8.2',
        'name=iPhone 6 Plus,OS=8.3',
        'name=iPhone 6 Plus,OS=8.4',
        'name=iPhone 6 Plus,OS=9.0',
      ]
    elsif platform == 'watchsimulator'
      [ 'name=Apple Watch - 38mm,OS=2.0',
        'name=Apple Watch - 42mm,OS=2.0',
      ]
    else
      []
    end
  end
else
  def destinations(platform: 'iphonesimulator')
    if platform == 'iphonesimulator'
      [ 'name=iPad 2,OS=8.1',
        'name=iPad Air,OS=8.1',
        'name=iPhone 4s,OS=8.1',
        'name=iPhone 4s,OS=8.4',
        'name=iPhone 5,OS=8.1',
        'name=iPhone 5s,OS=8.1',
        'name=iPhone 6,OS=8.1',
        'name=iPhone 6,OS=8.2',
        'name=iPhone 6,OS=8.4',
        'name=iPhone 6 Plus,OS=8.1',
        'name=iPhone 6 Plus,OS=8.2',
        'name=iPhone 6 Plus,OS=8.4',
      ]
    elsif platform == 'watchsimulator'
      [ 'name=Apple Watch - 38mm,OS=2.0',
        'name=Apple Watch - 42mm,OS=2.0',
      ]
    else
      []
    end
  end
end

def schemes
  ['UICKeyChainStore', 'libUICKeyChainStore']
end

if xcode_version.start_with?('7.0')
  def supportedPlatforms
    ['macosx', 'iphoneos', 'iphonesimulator', 'watchos', 'watchsimulator']
  end
elsif xcode_version.start_with?('6')
  def supportedPlatforms
    ['macosx', 'iphoneos', 'iphonesimulator']
  end
else
  def supportedPlatforms
    ['macosx', 'iphoneos', 'iphonesimulator', 'watchos', 'watchsimulator', 'appletvos', 'appletvsimulator']
  end
end

def configurations
  ['Debug', 'Release']
end

desc "build for all platforms"
task :build do |t|
  supportedPlatforms
    .product(configurations)
    .map { |platform, configuration| Rake::Task["build:#{platform}:#{configuration.downcase}"] }
    .map(&:invoke)
end

namespace :build do
  schemes.each do |scheme|
    supportedPlatforms.product(configurations).each do |platform, configuration|
      XCJobs::Build.new("#{platform}:#{configuration.downcase}") do |t|
        t.project = 'UICKeyChainStore'
        t.scheme = scheme
        t.sdk = platform
        if xcode_version.start_with?('8.0')
          if platform == 'iphonesimulator'
            t.add_destination('name=iPhone 6,OS=10.0')
          elsif platform == 'watchsimulator'
            t.add_destination('name=Apple Watch - 42mm,OS=3.0')
          elsif platform == 'appletvsimulator'
            t.add_destination('name=Apple TV 1080p,OS=10.0')
          end
        elsif xcode_version.start_with?('7.3') || xcode_version.start_with?('7.2')
          if platform == 'iphonesimulator'
            t.add_destination('name=iPhone 6,OS=9.2')
          elsif platform == 'watchsimulator'
            t.add_destination('name=Apple Watch - 42mm,OS=2.1')
          elsif platform == 'appletvsimulator'
            t.add_destination('name=Apple TV 1080p,OS=9.1')
          end
        end
        t.configuration = configuration
        t.build_dir = 'build'
        t.formatter = 'xcpretty -c'
        if ENV['CI']
          t.add_build_setting('CODE_SIGN_IDENTITY', '')
          t.add_build_setting('CODE_SIGNING_REQUIRED', 'NO')
        end
      end
    end
  end
end

namespace :test do
  supportedPlatforms
    .select { |platform| platform == 'macosx' || platform.end_with?('simulator') }.map do |platform|
      task platform do |t|
        configurations
          .map { |configuration| Rake::Task["test:#{platform}:#{configuration.downcase}"] }
          .map(&:invoke)
      end
    end
end
    
namespace :test do
  supportedPlatforms.product(configurations).each do |platform, configuration|
    XCJobs::Test.new("#{platform}:#{configuration.downcase}") do |t|
      t.project = 'UICKeyChainStore'
      t.scheme = 'UICKeyChainStore'
      t.sdk = platform
      destinations(platform: platform).each do |destination|
        t.add_destination(destination)
      end
      t.configuration = configuration
      if xcode_version.to_i >= 7
        t.coverage = true
      end
      t.build_dir = 'build'
      t.formatter = 'xcpretty -c'
    end
  end
  
  task :carthage do
    sh 'echo "github \"kishikawakatsumi/UICKeyChainStore\" \"${sha:-master}"\" > Cartfile'
    sh 'carthage update --no-use-binaries'
  end
end

XCJobs::Coverage::Coveralls.new()
